import Link from "next/link";
import fs from "fs";
import path from "path";

// Read the registry file generated by the build script
async function getComponents() {
  const registryPath = path.join(process.cwd(), "public/registry.json");
  if (!fs.existsSync(registryPath)) return [];
  const data = fs.readFileSync(registryPath, "utf8");
  return JSON.parse(data);
}

export default async function DocsPage() {
  const components = await getComponents();

  return (
    <div className="min-h-screen bg-black text-white p-8 sm:p-20 font-[family-name:var(--font-geist-sans)]">
      <div className="max-w-4xl mx-auto">
        <div className="mb-12">
          <Link href="/" className="text-zinc-500 hover:text-white mb-4 block">
            ← Back
          </Link>
          <h1 className="text-4xl font-bold mb-4">Documentation</h1>
          <p className="text-xl text-zinc-400">
            Welcome to the tomcs documentation. Here you can find all the
            components available in the registry.
          </p>
        </div>

        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-6 border-b border-zinc-800 pb-2">
            Getting Started
          </h2>
          <div className="prose prose-invert">
            <p className="text-zinc-300 mb-4">
              Tomcs is a collection of re-usable components. You don't verify
              dependencies, you copy and paste the code into your project.
            </p>
            <div className="bg-zinc-900 p-4 rounded-md border border-zinc-800 font-mono text-sm mb-4">
              <code>npx tomcs init</code>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-6 border-b border-zinc-800 pb-2">
            Components
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {components.map((component: any) => (
              <div
                key={component.slug}
                className="border border-zinc-800 rounded-lg p-6 hover:border-zinc-600 transition-colors"
              >
                <h3 className="text-xl font-bold mb-2">{component.name}</h3>
                <p className="text-sm text-zinc-500 mb-4">
                  Category: {component.category}
                </p>
                <div className="bg-zinc-950 p-3 rounded border border-zinc-900 font-mono text-xs text-zinc-400 mb-4 overflow-x-auto">
                  npx tomcs add {component.slug}
                </div>
                {/* In a full implementation, you would link to a detail page */}
                {/* <Link href={`/docs/components/${component.slug}`} className="text-blue-400 hover:underline">View Component →</Link> */}
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
